/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 air-fryer-transformed.glb -T 
Files: air-fryer-transformed.glb [4.16MB] > C:\Users\leech\Documents\!magnus_portfolio\!magnus_portfolio\src\asset\assets\public\models\air-fryer-transformed-transformed.glb [267.26KB] (94%)
Author: 3Dtiptut (https://sketchfab.com/3Dtiptut)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/5l-explore-6-air-fryer-64e2bae3914a4bb3a8b73334637f4d4d
Title: 5L Explore 6 air fryer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Aifryer(props) {
  const { nodes, materials } = useGLTF('/portfoliosite/public/models/air-fryer-transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials.material} position={[-1.762, 11.839, 17.097]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/portfoliosite/public/models/air-fryer-transformed-transformed.glb')
